name: Artifacts (Package)

on: [push, pull_request, workflow_dispatch]

jobs:
  artifacts-steamrt-sniper:
    runs-on: ubuntu-latest
    container: 
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
      options: --user 1001

    steps:

    - name: git gud
      run: |
        cat /etc/passwd
        USER root
        apt-get update
        apt-get install -y git
        USER 1001
    
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Blisto91/problem-matcher-testing/@main
      with:
        skip-directories: |
          "subprojects
          frog
           æøå "

    - name: Build release
      id: build-release
      shell: bash
      run: |
        git config --global --add safe.directory "$(pwd)"
        export VERSION_NAME="${GITHUB_REF##*/}-${GITHUB_SHA##*/}"
        ./package-native.sh ${VERSION_NAME} build
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
