name: Artifacts (Package)

on: [push, pull_request, workflow_dispatch]

jobs:
  artifacts-mingw-w64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Blisto91/problem-matcher-testing/@main

    - name: Build release
      id: build-release
      run: |
        export VERSION_NAME="${GITHUB_REF##*/}-${GITHUB_SHA##*/}"
        ./package-release.sh ${VERSION_NAME} build --no-package
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
